[project]
name = "poker-refactor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "dataclasses>=0.8",
    "types-colorama>=0.4.15.20240311",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
